### PR TITLE
[DOC] Updated broken links in the README and contributing docs files

### LINKED ISSUE #817: [DOC] Update broken links after PyJanitor Dev migration
# Brief Description of Fix
- After switching ownership to the pyjanitor-dev organization, a number of links in the README and repo description have dead links
- ericmjl -> pyjanitor-devs
- Helpful resource potentially: https://github.com/JustinBeckwith/linkinator

### PR DESCRIPTION
**Pull request by nvamsikrishna05**
# PR Description

Please describe the changes proposed in the pull request:

- Updated the Broken Links in the README and Contributing doc files.

**This PR resolves #817 **

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl
- @loganthomas
- @samukweku

### CODE REVIEW

**Review by samukweku — APPROVED** [review]

**Comment by samukweku** [comment]
@nvamsikrishna05 kindly fix the failing checks.

**Comment by samukweku** [comment]
@nvamsikrishna05 have a look at the notebook and kindly resolve it, using the same idea as your other PR

**Comment by nvamsikrishna05** [comment]
@samukweku It's the same issue as other PR, so I am waiting for that PR to merge and will update this after that.

**Comment by ericmjl** [comment]
@nvamsikrishna05 we're good to merge in the latest dev branch! Can you do that? I'll be able to do a reviw shortly. :smile:

**Comment by nvamsikrishna05** [comment]
@ericmjl Updated the PR. you can review it now. Thanks.

**Review by loganthomas — APPROVED** [review]
Looks good to me. Thanks @nvamsikrishna05!

**Comment by ericmjl** [comment]
With @samukweku and @loganthomas both finishing the review, I'm good to go too.

**Comment by ericmjl** [comment]
Thanks @nvamsikrishna05!

**Pull request merged**
