### PR TITLE
[DOC]: added pipenv installation instructions

### LINKED ISSUE #763: Add pipenv installation guide to docs, specifying to allow prereleases
# Instructions for how to install pyjanitor via pipenv

Some folks might use pipenv for environment management. The recent update requires a prerelease dependency (black, as mentioned in [760](https://github.com/ericmjl/pyjanitor/issues/760)). I'd like to update the installation page of the documentation so that it A) includes pipenv installation and B) let's users know that they need to allow prereleases.

Something to the effect of : 
>Installation of `pyjanitor` through pipenv requires you to allow prereleases:
>```bash
>pipenv install --pre pyjanitor
>```

# Relevant Context

- [Installation page](https://pyjanitor.readthedocs.io/installation.html)
- [README (I assume this is the source of the installation page?)](https://github.com/ericmjl/pyjanitor/blob/dev/README.rst)

### PR DESCRIPTION
**Pull request by evan-anderson-ts**
# PR Description

- Added instructions for pipenv installation of pyjanitor.
- Fixed my contribution link.

**This PR resolves https://github.com/ericmjl/pyjanitor/issues/763.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.
My [evan-anderson](https://github.com/evan-anderson) account is already on the author page.

3. [x] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

** I encountered the following errors: ** 
image
However, I didn't make any changes to code, only documentation in the readme. @ericmjl please let me know if I need to address any problems here!

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

My changes render correctly, but I encountered a number of errors that seem unrelated to my doc changes:

```
Building documentation...
cd docs && make html
make[1]: Entering directory '/workspaces/pyjanitor/docs'
Running Sphinx v3.1.1
Making symlink to ../examples/notebooks
notebooks directory already exists. Not creating..
loading pickled environment... done
[autosummary] generating autosummary for: CONTRIBUTION_TYPES.rst, PYCHARM_USERS.rst, authors.rst, contributing.rst, index.rst, installation.rst, notebooks.rst, notebooks/Pivoting Data from Wide to Long.ipynb, notebooks/README.rst, notebooks/Row_to_Names.ipynb, ..., reference/janitor.functions/janitor.unionize_dataframe_categories.md, reference/janitor.functions/janitor.update_where.md, reference/janitor.spark.functions/janitor.spark.clean_names.md, reference/janitor.spark.functions/janitor.spark.update_where.md, reference/janitor.xarray.functions/janitor.xarray.clone_using.md, reference/janitor.xarray.functions/janitor.xarray.convert_datetime_to_number.md, reference/ml.rst, reference/pyspark.rst, reference/timeseries.rst, reference/xarray.rst
[autosummary] generating autosummary for: /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.add_column.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.add_columns.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.bin_numeric.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.change_type.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.clean_names.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.coalesce.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.collapse_levels.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.concatenate_columns.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.convert_excel_date.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.convert_matlab_date.md, ..., /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.take_first.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.then.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.to_datetime.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.transform_column.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.transform_columns.md, /workspaces/pyjanitor/docs/reference/janitor.functions/janitor.update_where.md, /workspaces/pyjanitor/docs/reference/janitor.spark.functions/janitor.spark.clean_names.md, /workspaces/pyjanitor/docs/reference/janitor.spark.functions/janitor.spark.update_where.md, /workspaces/pyjanitor/docs/reference/janitor.xarray.functions/janitor.xarray.clone_using.md, /workspaces/pyjanitor/docs/reference/janitor.xarray.functions/janitor.xarray.convert_datetime_to_number.md
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 54 source files that are out of date
updating environment: 0 added, 58 changed, 0 removed
reading sources... [100%] reference/janitor.xarray.functions/janitor.xarray.convert_datetime_to_number                                                                  
/workspaces/pyjanitor/docs/notebooks/board_games.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_board_games_24_0.png
/workspaces/pyjanitor/docs/notebooks/french_trains.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_french_trains_20_1.png
/workspaces/pyjanitor/docs/notebooks/inflating_converting_currency.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_inflating_converting_currency_9_1.svg
/workspaces/pyjanitor/docs/notebooks/inflating_converting_currency.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_inflating_converting_currency_9_1.png
/workspaces/pyjanitor/docs/notebooks/inflating_converting_currency.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_inflating_converting_currency_13_1.svg
/workspaces/pyjanitor/docs/notebooks/inflating_converting_currency.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_inflating_converting_currency_13_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:15: WARNING: File not found: 'reference/functions.html#janitor.functions.min_max_scale'
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:17: WARNING: File not found: 'reference/functions.html#janitor.functions.transform_column'
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:452: WARNING: File not found: 'reference/functions.html#janitor.functions.min_max_scale'
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:1329: WARNING: File not found: 'reference/functions.html#janitor.functions.transform_columns'
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_10_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_12_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_14_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_19_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_21_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_23_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_27_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_29_1.png
/workspaces/pyjanitor/docs/notebooks/normalize.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_normalize_31_1.png
/workspaces/pyjanitor/janitor/functions.py:docstring of janitor.currency_column_to_numeric:16: WARNING: Bullet list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /workspaces/pyjanitor/docs/CONTRIBUTION_TYPES.rst: WARNING: document isn't included in any toctree
/workspaces/pyjanitor/docs/PYCHARM_USERS.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] reference/xarray                                                                                                                               
generating indices...  genindex py-modindexdone
copying notebooks ... [100%] notebooks/normalize.ipynb                                                                                                                  
highlighting module code... [100%] janitor.xarray.functions                                                                                                             
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 22 warnings.

The HTML pages are in _build/html.
make[1]: Leaving directory '/workspaces/pyjanitor/docs'
```

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by evan-anderson-ts** [comment]
One other quick question / comment: running `make docs` made a bunch of changes to the files in `docs/reference`. It looks like it deleted the last blank line of each of these markdown files. I decided not to commit these changes, but let me know if I should!
image

**Comment by ericmjl** [comment]
Thanks @evan-anderson-ts! Everything looks great here.

**Review by ericmjl — APPROVED** [review]

**Comment by samukweku** [comment]
@evan-anderson-ts , if you can, kindly update the branch on your end, to fix the conflicting files, so I can approve and merge. Thanks!

**Comment by evan-anderson-ts** [comment]
@samukweku Hi Sam -- I resolved the conflicts! Let me know if you need anything else 😁

**Review by samukweku — APPROVED** [review]

**Comment by ericmjl** [comment]
Merging, thanks @evan-anderson-ts!

**Pull request merged**
