### PR TITLE
[DOC] Fix column name in docstring example

### LINKED ISSUE #963: Example of groupby_agg shows wrong output
# Brief Description of Fix

Currently, the docs for `groupby_agg` uses `new_column_name='count'` but the result shown in the docs has column name 'size'.

image

The correct column name should be 'count'.

image

```
   group  var1  count
0      1     1      4
1      1     1      4
2      1     1      4
3      1     1      4
4      1     2      1
5      2     1      1
6      2     2      3
7      2     2      3
8      2     2      3
9      2     3      1
```

Seems like a simple enough fix, I'm happy to open a PR if you'ld like

# Relevant Context

- [Link to documentation page](https://pyjanitor-devs.github.io/pyjanitor/api/functions/#janitor.functions.groupby_agg)
- [Link to exact file to be edited](https://github.com/pyjanitor-devs/pyjanitor/blob/dev/janitor/functions/groupby_agg.py)

### PR DESCRIPTION
**Pull request by thatlittleboy**
# PR Description

Please describe the changes proposed in the pull request:

- simple docstring example fix (use of `new_column_name` should be respected in the output)
- I also took the liberty to fix some other minor spacing/formatting 

**This PR resolves #963.**

# PR Checklist

Please ensure that you have done the following:

1. [X] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by thatlittleboy** [comment]
I think I'll pass on including myself into AUTHORS.rst, this is just a really minor fix.

**Review by samukweku — APPROVED** [review]

**Comment by samukweku** [comment]
@thatlittleboy no contribution is too small; kindly add your name to the authors.rst page; and thanks again for this.

**Comment by thatlittleboy** [comment]
Is there anything I need to fix here?

**Comment by ericmjl** [comment]
I think there's something borked in the CI, that's going to need fixing first. Hang tight, @thatlittleboy!

**Comment by ericmjl** [comment]
@thatlittleboy could you update this branch with the latest dev branch please?

**Pull request merged**
