### PR TITLE
[ENH] variable args for `complete`

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Uses variable args (*args) for the `complete` function.

**This PR improves `complete` function API.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl 
- @hectormz
- @nvamsikrishna05 
- @loganthomas

### CODE REVIEW

**Comment by samukweku** [comment]
noticed that the docs are not rendering properly (links not working etc). @ericmjl @hectormz might need a refresher on what to check

**Review by ericmjl — APPROVED** [review]
Wonderful work, @samukweku! I love the direction you've taken here, making the API much more uniform with variable args :smile:

**Comment by ericmjl** [comment]
@samukweku could you resolve the conflicts and then ping back here? I think the PR has been open long enough that we should merge. :smile:

**Comment by ericmjl** [comment]
Thanks @samukweku!

**Pull request merged**
