### PR TITLE
[ENH] Updates to Pivot longer

### LINKED ISSUE #885: [BUG] Weird output with pivot_longer
# Brief Description

`pivot_longer` outputs wrong results when a sequence is used in `names_pattern`

# System Information

- Operating system:Linux
- Python version (required): 3.9

# Minimally Reproducible Code

```python
import pandas as pd
import numpy as np
import janitor as jn

df = pd.DataFrame(
            {
                "id": [1, 2, 3],
                "x1": [4, 5, 6],
                "x2": [5, 6, 7],
                "y1": [7, 8, 9],
                "y2": [10, 11, 12],
            }
        )

df

   id  x1  x2  y1  y2
0   1   4   5   7  10
1   2   5   6   8  11
2   3   6   7   9  12


# works fine when there are multiple values in names_pattern
In [5]: df.pivot_longer('id', names_to=('x', 'y'), names_pattern=('x', 'y'))
Out[5]: 
   id  x   y
0   1  4   7
1   2  5   8
2   3  6   9
3   1  5  10
4   2  6  11
5   3  7  12

# Wrong output for a single value

In [6]: df = df.iloc[:, :3]

In [8]: df
Out[8]: 
   id  x1  x2
0   1   4   5
1   2   5   6
2   3   6   7


In [7]: df.pivot_longer('id', names_to=('x',), names_pattern=('x',)) # where did x go?
Out[7]: 
   id
0   1
1   2
2   3
3   1
4   2
5   3
```

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Fix bug in #885 where names_pattern returns wrong output
- Prune functions to cover small sections (one for names_sep, one for names_pattern)
- Technical debt reduced (hopefully)
- Speed improvements : 
```python
df = pd.DataFrame({
    'famid': [1, 1, 1, 2, 2, 2, 3, 3, 3],
    'birth': [1, 2, 3, 1, 2, 3, 1, 2, 3],
    'ht1': [2.8, 2.9, 2.2, 2, 1.8, 1.9, 2.2, 2.3, 2.1],
    'ht2': [3.4, 3.8, 2.9, 3.2, 2.8, 2.4, 3.3, 3.4, 2.9]
})

df

   famid  birth  ht1  ht2
0      1      1  2.8  3.4
1      1      2  2.9  3.8
2      1      3  2.2  2.9
3      2      1  2.0  3.2
4      2      2  1.8  2.8
5      2      3  1.9  2.4
6      3      1  2.2  3.3
7      3      2  2.3  3.4
8      3      3  2.1  2.9


In [401]: %timeit pd.wide_to_long(df, stubnames='ht', i=['famid', 'birth'], j='age')
13.5 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

# this PR
In [403]: %%timeit
     ...: df.pivot_longer(index=['famid','birth'],
     ...:                 names_to=('.value', 'age'),
     ...:                 names_pattern=r"(ht)(\d)")
     ...: 
8.11 ms ± 233 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# dev
In [404]: %%timeit
     ...: df.pivot_longer(index=['famid','birth'],
     ...:                 names_to=('.value', 'age'),
     ...:                 names_pattern=r"(ht)(\d)")
10.8 ms ± 275 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

df = pd.concat([df]*10_000, ignore_index=True)
df['famid'] = np.arange(len(df)) #wide_to_long requires unique id


In [410]: %timeit pd.wide_to_long(df, stubnames='ht', i=['famid', 'birth'], j='age')
238 ms ± 3.15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [411]: %%timeit   # dev
     ...: df.pivot_longer(index=['famid','birth'],
     ...:                 names_to=('.value', 'age'),
     ...:                 names_pattern=r"(ht)(\d)")
     ...: 
43.8 ms ± 423 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [412]: %%timeit  # dev
     ...: df.pivot_longer(index=['famid','birth'],
     ...:                 names_to=('.value', 'age'),
     ...:                 names_pattern=r"(ht)(\d)", sort_by_appearance=True)
     ...: 
     ...: 
53.1 ms ± 651 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [414]: %%timeit  # this PR
     ...: df.pivot_longer(index=['famid','birth'],
     ...:                 names_to=('.value', 'age'),
     ...:                 names_pattern=r"(ht)(\d)", sort_by_appearance=True)
     ...: 
     ...: 
42.9 ms ± 317 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [415]: %%timeit  # this PR
     ...: df.pivot_longer(index=['famid','birth'],
     ...:                 names_to=('.value', 'age'),
     ...:                 names_pattern=r"(ht)(\d)", sort_by_appearance=False)
     ...: 
     ...: 
33.4 ms ± 374 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

The bug for #885  is fixed as well:

```python

   id  x1  x2
0   1   4   5
1   2   5   6
2   3   6   7

In [476]:  df.pivot_longer('id', names_to=('x',), names_pattern=('x',))
Out[476]: 
   id  x
0   1  4
1   2  5
2   3  6
3   1  5
4   2  6
5   3  7

```

**This PR resolves #885 **

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
This is a substantial PR, @samukweku, and I really like the profiling that you did! I'm going to take a day or two to review it.

**Comment by samukweku** [comment]
No rush @ericmjl, i delayed this for quite some time,

**Review by ericmjl — APPROVED** [review]
Admittedly this is a big PR. With my approval on this PR, I'm trusting your skill level and familiarity with the codebase, @samukweku :smile:

**Comment by ericmjl** [comment]
@samukweku I'm going to merge this one in. It's been open long enough.

**Pull request merged**
