### PR TITLE
[ENH] Pivot longer - allow multiple `.value`

### LINKED ISSUE #1034: [ENH] Allow `pivot_longer` to support multiple `.value`
# Brief Description

Allowing multiple `.value` could make some transformations simpler

# Example API

inspiration from [here](https://github.com/tidyverse/tidyr/issues/619#issuecomment-725530922)
```python
   x_1_mean  x_2_mean  x_1_sd  x_2_sd  y_1_mean  y_2_mean  y_1_sd  y_2_sd  unit
0         1         1       0   0.739         1         1       0  -0.525     1
1         2         1       1   0.219         2         1       1   0.623     2
2         3         0       1   1.460         3         0       1  -0.705     3
3         4         0       1   0.918         4         0       1   0.662     4

df.pivot_longer(index = 'unit', 
                names_to = (".value","time", ".value"), 
                names_pattern = r"(x|y)_([0-9])(_mean|_sd)")

   unit  time  x_mean   x_sd  y_mean   y_sd
0     1     1       1  0.000       1  0.000
1     1     2       1  0.739       1 -0.525
2     2     1       2  1.000       2  1.000
3     2     2       1  0.219       1  0.623
4     3     1       3  1.000       3  1.000
5     3     2       0  1.460       0 -0.705
6     4     1       4  1.000       4  1.000
7     4     2       0  0.918       0  0.662

# current approach involves a combination of pivot_longer and pivot_wider
(df
.pivot_longer('unit', names_to = ('letter', 'time', '.value'), names_sep = '_')
.pivot_wider(index = ['unit', 'time'], names_from = 'letter', levels_order = ['letter', None])
)
```

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Support multiple `.value` 
- Refactored tests
- Add test for scenarios where there is only one names_to and names_pattern is provided

**This PR resolves #1034.**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1035--pyjanitor.netlify.app

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
Approving! Knowing that 100% of the diff is hit is good enough for me :smile:.

**Comment by ericmjl** [comment]
Btw, @samukweku, it appears your commits are coming from the account `sammychoco`?

**Comment by samukweku** [comment]
@ericmjl yea, connected from another machine and I forgot to change my GitHub details for that ... long story ... had to create anoda GitHub account for a separate project

**Comment by thatlittleboy** [comment]
Something seems up with the diff @samukweku , can you fix it first, then I'll submit my review after. Thanks!

**Comment by samukweku** [comment]
@thatlittleboy resolved d documentation build failure.

**Comment by thatlittleboy** [comment]
@samukweku Under "Files Changed", there are still alot of changes unrelated to the current PR appearing (which were merged into dev before), which makes it a little confusing to review. It seems git diff is getting confused because of a conflict with the CHANGELOG file.

Could you do a rebase of your `pivot_longer_enh` branch on top of the current `dev`, and `git push --force-with-lease` up again? It'll make the PR a lot cleaner. Just ensure your local branches are all in-sync with the remote (origin) before you start rebasing.

You will encounter 1 conflict while you're rebasing (which is the conflict on the CHANGELOG mentioned above). Just fix that conflict locally, commit the changes in, then `git rebase --continue` and all should be well and good.

**Comment by samukweku** [comment]
@thatlittleboy  my git fu is horrible; way easier (and escapist) for me to start a new PR #1039

**Pull request closed without merging**
