### PR TITLE
[ENH] generic select function

### LINKED ISSUE #1124: replicate `select_columns` on the index
select_columns can be adapted to index selection as well; not sure about the name though  ---> select_index/select_rows?

```py
df.select_index()
df.select_rows()
```

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Fix blank note output in the docs for `select_rows`, `select_columns`
- generic select function that accepts both rows and columns

**This PR resolves #1124 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1187--pyjanitor.netlify.app

**Review by ericmjl — APPROVED** [review]

**Comment by Zeroto521** [comment]
Hi, I thought we could add some marks to notify users that` select_*` methods are new coming.
Details see #1188

**Comment by Zeroto521** [comment]
The codecov is decreasing.
Let's merge the dev branch new changes (#1185).
See codecov whether could back to normal.

**Review by ericmjl — APPROVED** [review]
Re-approving!

**Comment by ericmjl** [comment]
Okie dokes, I think we should merge. The PR has been open long enough!

**Pull request merged**
