### PR TITLE
[ENH] Complete refactor

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Uses `expand_grid` to generate cartesian index.
- Add `by` parameter, allowing `complete` to work with `groupby`.
- Add groupby example to function.

**This PR improves the `complete` function.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [x] Ensure that you have added tests.
- [x] Run all tests (`$ pytest .`) locally on your machine.
    - [x] Check to ensure that test coverage covers the lines of code that you have added.
    - [x] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by samukweku** [comment]
@ericmjl ; how do I view the lines of code that fail codecov?

**Comment by samukweku** [comment]
@ericmjl  when I try viewing the PR on codecov to see the lines causing the issue, I get this message:

image

**Comment by ericmjl** [comment]
~@samukweku, I think you'll need a codecov account too. Let's take it to discord.~

Oops, I wrote too fast :joy_cat:. Let me debug and see what's going on there. I've noticed the most recent PRs failing that way too.

**Review by ericmjl — APPROVED** [review]
Appreciate the quality work from you, @samukweku!

**Comment by ericmjl** [comment]
Let's merge, I think this one is good to go, let's merge.

**Pull request merged**
