### PR TITLE
non-equi join rewrite numba

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- reimplementation of the algorithm that powers the non-equi join in numba
- more info in the docs regarding range joins, and where numba can be helpful
- improved performance for numba for range joins and multiple non equi joins when getting first/last match

**This PR improves conditional_join.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1341--pyjanitor.netlify.app

**Comment by ericmjl** [comment]
@samukweku is this one ready for review? On GitHub it looks like it's still being marked as a draft.

**Comment by samukweku** [comment]
@ericmjl not yet, still got some optimisations that I am hopeful to pull off

**Comment by samukweku** [comment]
@ericmjl  not familiar with the jitter function. can i get your help with the failing test function. thanks

**Comment by ericmjl** [comment]
> @ericmjl not familiar with the jitter function. can i get your help with the failing test function. thanks

Not a problem, @samukweku. I encountered a similar issue when testing locally so I decided to make the test a bit more lenient.

**Comment by ericmjl** [comment]
@samukweku, apologies for the long turnaround time here. I think we should merge this in, as (a) the PR has been open for a long time, and (b) I've already committed to the branch. Once the CI checks are done, I'll do a merge!

**Comment by ericmjl** [comment]
@samukweku I have merged! Thank you for taking care of pyjanitor, I really appreciate it!

**Pull request merged**
