### PR TITLE
[BUG] Fix deprecation warning for pivot_longer

### LINKED ISSUE #1308: deprecation warning for pivot_longer
# Brief Description

deprecation warning for `pivot_longer` when running multiple `names_to` and `values_to`.

# System Information

- Operating system: Linux
- OS details (optional):  Ubuntu
- Python version (required): 3.10

# Minimally Reproducible Code

```
df
   id  c1  c2  c3  oc_1  oc_2  oc_3  oc_4 gc_1  ... pf_4 V1_1 V1_2 V1_3 V1_4 S1_1 S1_2  S1_3  S1_4
0   1  1c  2c  3c     1     0     1     1   T1  ...  PF4   11   12   13   14   21   22    23    24

[1 rows x 24 columns]

( df
.pivot_longer(
    index=slice('id','c3'),
    names_to=['a','b','c','VAR'],
    values_to=['oc','gc','pf','Value'],
    names_pattern=['oc','gc','pf','V|S'],
    ignore_index=False)
)
```

# Error Messages

```
/home/sam/mambaforge/envs/normal/lib/python3.9/site-packages/janitor/functions/pivot.py:1275: DeprecationWarning: Series._data is deprecated and will be removed in a future version. Use public APIs instead.
  df.columns = [mapping, positions]
```

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Fixes deprecation warning for pivot_longer

**This PR resolves #1308 **

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1309--pyjanitor.netlify.app

**Comment by ericmjl** [comment]
# GitBot Summary of Changes

The pull request includes several changes across two files: CHANGELOG.md and janitor/functions/pivot.py. 

In CHANGELOG.md, the changes include:
- Added the author's name (@samukweku) to the enhancement of `conditional_join` supporting timedelta dtype.
- Added a bug fix for a deprecation warning in `pivot_longer`.

In janitor/functions/pivot.py, the changes include:
- Updated the method to ensure uniqueness of column names in `_computations_pivot_longer`.
- Refactored the `_pivot_longer_dot_value` function to handle multiple \".value\" columns and improved memory management.
- Updated the method of assigning column names in `_pivot_longer_dot_value` and `_headers_single_series` to use `pd.MultiIndex.from_arrays`.

cc: @samukweku, please check for correctness!

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
I think this one is good to merge as well, right @samukweku?

**Comment by samukweku** [comment]
thanks @ericmjl for the reviews

**Comment by samukweku** [comment]
closed in favour of #1321

**Pull request closed without merging**
