### PR TITLE
[INF] Fix missing long documentation in PyPI README

### LINKED ISSUE #1199: [DOC] Missing Pyjanitor description on PyPi
# Brief Description of Fix

Since `pyjanitor` release `0.22.0`, there has not been a ["Project description" for the package on PyPi](https://pypi.org/project/pyjanitor/0.22.0/#description).

During the release of of `0.24.0`, @samukweku and I got an error during the release process due to:

```
Checking dist/pyjanitor-0.24.0-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         No content rendered from RST source.     
```
Our guess is that we had switched the README from RST to MD some time ago, causing the `long_description` to quietly fail, and now the `gh-action-pypi-publish` GitHub action would no longer accept the bad `long_description`.

We updated the `long_description_content_type` in `setup.py` to markdown  in #1197  and the package was successfully published to PyPi, but there is still no Project description. So there must still be something that is not being generated correctly.

We need to verify that `long_description` is properly being generated. We should test with local tools *and* https://test.pypi.org/ to verify that this is fixed.

### PR DESCRIPTION
**Pull request by thatlittleboy**
# PR Description

Please describe the changes proposed in the pull request:

**This PR resolves #1199.** See discussion in attached issue.

Use `<!-- pypi-doc -->` as a boundary marker instead of `.. pypi-doc` since we moved to markdown from rst. There should be no visible difference to the github README and to the documentation page.

After fixing, `twine check` no longer throws a warning about missing `long-description`, and I've confirmed that the long description gets compiled into the package metadata, so PyPI should be able to pick it up from there now.

--- 

I followed the pypi-doc boundary markers from previously. For the record, here is the resulting long description output:

<details>
  <summary><b>Long description output</b></summary>
  
`pyjanitor` is a Python implementation of the R package [`janitor`][janitor], and
provides a clean API for cleaning data.

[janitor]: https://github.com/sfirke/janitor

## Quick start

- Installation: `conda install -c conda-forge pyjanitor`
- Check out the collection of [general functions](https://pyjanitor-devs.github.io/pyjanitor/api/functions/)

## Why janitor?

Originally a port of the R package,
`pyjanitor` has evolved from a set of convenient data cleaning routines
into an experiment with the [`method chaining`][mc] paradigm.

[mc]: https://towardsdatascience.com/the-unreasonable-effectiveness-of-method-chaining-in-pandas-15c2109e3c69

Data preprocessing usually consists of a series of steps
that involve transforming raw data into an understandable/usable format.
These series of steps need to be run in a certain sequence to achieve success.
We take a base data file as the starting point,
and perform actions on it,
such as removing null/empty rows,
replacing them with other values,
adding/renaming/removing columns of data,
filtering rows and others.
More formally, these steps along with their relationships
and dependencies are commonly referred to as a Directed Acyclic Graph (DAG).

The `pandas` API has been invaluable for the Python data science ecosystem,
and implements method chaining of a subset of methods as part of the API.
For example, resetting indexes (`.reset_index()`),
dropping null values (`.dropna()`), and more,
are accomplished via the appropriate `pd.DataFrame` method calls.

Inspired by the ease-of-use
and expressiveness of the `dplyr` package
of the R statistical language ecosystem,
we have evolved `pyjanitor` into a language
for expressing the data processing DAG for `pandas` users.

## Installation

`pyjanitor` is currently installable from PyPI:

```bash
pip install pyjanitor
```

`pyjanitor` also can be installed by the conda package manager:

```bash
conda install pyjanitor -c conda-forge
```

`pyjanitor` can be installed by the pipenv environment manager too. This requires enabling prerelease dependencies:

```bash
pipenv install --pre pyjanitor
```

`pyjanitor` requires Python 3.6+.

## Functionality

Current functionality includes:

- Cleaning columns name (multi-indexes are possible!)
- Removing empty rows and columns
- Identifying duplicate entries
- Encoding columns as categorical
- Splitting your data into features and targets (for machine learning)
- Adding, removing, and renaming columns
- Coalesce multiple columns into a single column
- Date conversions (from matlab, excel, unix) to Python datetime format
- Expand a single column that has delimited, categorical values
  into dummy-encoded variables
- Concatenating and deconcatenating columns, based on a delimiter
- Syntactic sugar for filtering the dataframe based on queries on a column
- Experimental submodules for finance, biology, chemistry, engineering, and pyspark

</details>

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1216--pyjanitor.netlify.app

**Comment by samukweku** [comment]
@thatlittleboy is it possible to attach a screenshot of the output - just to confirm that it works as expected on the pypi page

**Review by samukweku — APPROVED** [review]

**Comment by thatlittleboy** [comment]
> @thatlittleboy is it possible to attach a screenshot of the output - just to confirm that it works as expected on the pypi page

Yep, you can see it here: https://test.pypi.org/project/thatlittleboy-pyjanitor/0.24.0/

image

**Review by ericmjl — APPROVED** [review]
Approving, LGTM!

**Pull request merged**
