### PR TITLE
[DOC] Migrate to google docstring style

### LINKED ISSUE #1032: [DOC/INF] Migrate mkdocs documentation style from sphinx to google
# The current state of affairs

1. The migration of pyjanitor's documentation from `Sphinx` to `mkdocs` happened late last year (#894).
    And with `mkdocstrings`, we’re [currently using the “restructured-text” docstring-style](https://github.com/pyjanitor-devs/pyjanitor/blob/eabc98858b56474d919e8f089dddb57c4b725ec5/mkdocs.yml#L49) option (which is not actually reST but rather "sphinx"-style docstrings, with `:param :`, `:returns:` etc.).
2. As of time of writing, there is an ongoing sprint on incorporating MWEs in all of our (public) APIs. (#972).
    So, having proper and nicely-formatted example blocks in our documentation is becoming more important moving forward.

# The issue(s)

### Upstream support is poor

From my interactions with the core-dev of `mkdocstrings`, and having gotten to know the `mkdocs` ecosystem better over the past week or so, I’ve realized that the restructured-text/sphinx docstring style **is not as well-supported** as the other styles (namely, google / numpy) by `mkdocstrings`.
For example, both the legacy python handler and new experimental python handler does not properly support the “examples” section in sphinx style at the moment (see [here-legacy](https://mkdocstrings.github.io/python-legacy/usage/#sections_1), and [here-new](https://mkdocstrings.github.io/griffe/docstrings/#section-support)).

And the new option to remove doctest flags (recently added to [pytkdocs](https://github.com/mkdocstrings/pytkdocs/pull/134) and [griffe](https://github.com/mkdocstrings/griffe/pull/48)) has only been implemented for Google/Numpy styles, but NOT for the reST / sphinx styles. --- as a direct consequence of the docstring collectors not supporting "examples" section mentioned above.

### Broken / Incomplete functionality

On the `pyjanitor` front: The following points could serve as their own individual issues/tickets on their own right, but just as an overview of what I’ve observed:
- doctest flags are visible in the rendered HTML (#1000);
- Extraneous space after the code block if there are no text after. (Note the space above the "Parameters" section)
   examples-current
- Example block is currently not rendered as a “semantic block” but rather as a (Markdown text + code block) group. This is also illustrated in the above screenshot. Whereas, if we use Google style, the "examples" section is natively supported, see a simple example below for what a proper Examples section should look like. The "Examples" header is bold; and text within the "examples" section are treated as such by the python docstrings collector (rather than being treated as "general text in the docstring").
    
- Not able to copy the example code without the chevrons `>>>` and `…`. Admittedly this would just be a nice functionality to have, since `ipython` supports copying and running code with these markers in them regardless.

I’m unsure how many of the above issues are due to `mkdocstrings` not completely supporting reST. At the very least, I'm sure the first issue about doctest flag can be resolved if we move to Google style.

### Using `sphinx`-style is not aligned with original motivation of migration

And echoing the original motivation of moving away from Sphinx build in the first place, I would argue that the Google style is more readable, easier to maintain, and more in the spirit of the `mkdocs` ecosystem, than the current sphinx style.

# The proposed solution

As per title, I propose shifting over to Google docstring style. Most of the effort towards this should revolve around
- changing the sphinx style `:param:`, `:returns:`, `:raises:` etc. to Google style (`Args:`, `Returns:`, `Raises:`)
- making the examples section look nicer (try to solve as many of the above issues as reasonably possible)

If we’re agreeable to this proposal, I think we can draw on the experience from the previous docs migration, so suggestions on how to practically carry this out would be very welcome. It will most likely be the next major step forward on the documentation-front, after #972 is resolved.

**Thoughts? Objections?**

## Addendum

Styles:
1. Google -- https://google.github.io/styleguide/pyguide.html#383-functions-and-methods
2. Numpy -- https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard

There seems to be an automated tool for converting reST to Google ([pyment](https://github.com/dadadel/pyment)), but I've tried it and it's quite buggy. We'll probably have to do the migration by hand.

### PR DESCRIPTION
**Pull request by thatlittleboy**
# PR Description

Please describe the changes proposed in the pull request:

- Migrate all "visible" (i.e., rendered into mkdocs) docstrings to Google style. For better compatibility with `mkdocstrings`.
- With this change, we can finally drop the dependency on the legacy python handler and use the newer python handler with `mkdocstrings`.
- Added a guidelines page on docstring style for future developers / contributors to follow.
- Update changelog.

**This PR relates to #1032.**

(There are other ideas raised in that issue that I would like to fix as well, hence not closing, but that's for a future PR)

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1235--pyjanitor.netlify.app

**Comment by thatlittleboy** [comment]
`darglint` is struggling with checking all of these files, and `pre-commit-CI` is timing out after 180s. And I can't find a way to extend this timeout.

I've run the pre-commit hooks locally, from 088b3f3 (dev) to 61dc66d (current HEAD before the changelog commit)

image

As for using ruff to replace darglint, it's not currently implemented yet so that's not an option for now.

---

But anyway, in better news, I think I've migrated all the public docstrings to Google style already (no guarantees on the private ones, though, I think I got most of them as well). PR is now ready for review! 🎉 

**Key review points**:

- updated the dependencies and relevant `mkdocs.yml` config
- look through the rendered documentation and see if there's anything that looks off


Thanks!

**Comment by ericmjl** [comment]
@thatlittleboy I spot-checked the Functions page, and it looks great!

This is quite a heroic effort 🎉

Thank you for handling this migration!

I think we shouldn't worry about pre-commit timing out unless it gives us a ton of problems in the future. In that case, we can always run our own pre-commit Action.

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
@samukweku and @Zeroto521 - the PR diff is large but conceptually, it's a small change. Between the two of you, whoever sees my comment first can just merge straight away if you don't want to spot-check things yourself. That way we'll get the updated docs into `dev` asap!

**Review by samukweku — APPROVED** [review]

**Pull request merged**
