### PR TITLE
[ENH] Updated convert_excel_date to throw meaningful error

### LINKED ISSUE #813: convert_excel_date throws error when input contains strings
After importing an excel sheet into a dataframe, applying the convert_excel_date throws an error, `ValueError: unit must not be specified if the input contains a str`, if the columns are objects with strings. The error comes from the [pandas.to_timedelta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_timedelta.html) function, which is rather confusing for the user at first.

Converting the column to numeric and then dropping inf and nan values fixes this issue (e.g. `df.column..apply(pd.to_numeric, errors='coerce',downcast='integer').astype('float').astype('Int64')` and then `df = df[~df[column].isin([np.nan, np.inf, -np.inf]).any(1)]`).

Perhaps the function should trap for this error and either convert when appropriate, remove the unit input when appropriate, or at the least tell the user what to do to fix the issue.

Also of note, the above conversion does a float and then an Int64 conversion because the Int64 conversion alone will fail if infinite or null values are in the set. The nan/inf drop is then necessary because the to_timedelta seems to require `int64` not `Int64` (the latter allowing nan values). Suggesting to the user that they should run the above first, and noting the null/inf issue, may be the best way to address this issue and trap for the relevant errors.

# System Information

- Operating system: Windows  
- Python version (required): 3.8

# Minimally Reproducible Code

`df_train=df_train.convert_excel_date('column_name')`

Unfortunately I can't share my excel sheet in this case to reproduce the error (proprietary), but importing date columns as objects that are string values and then running the above function on that column causes the error.

### PR DESCRIPTION
**Pull request by nvamsikrishna05**
…ues are of type non-numeric

# PR Description

Please describe the changes proposed in the pull request:

- Updated convert_excel_date function to throw meaningful error when input column contains non-numeric data.

**This PR resolves #813 **

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl
- @loganthomas 
- @samukweku

### CODE REVIEW

**Review by samukweku — APPROVED** [review]

**Comment by samukweku** [comment]
@nvamsikrishna05 kindly have a look at the failing checks and resolve

**Comment by nvamsikrishna05** [comment]
@samukweku I resolved the code formatting and linting check which were failing. Now they are passing. But one of the jupyter notebook is failing at the finance functions which wasn't modified in this pr.

I ran the same notebook in colab and it was running properly for me. Can you help me out with what's the issue ?

**Comment by samukweku** [comment]
@nvamsikrishna05 for the failing notebook, change current year value to `int(x.name)`

**Comment by nvamsikrishna05** [comment]
@samukweku Thanks, it worked. All Tests passed now. If you see there's no other issue you can merge the PR.

**Comment by samukweku** [comment]
@nvamsikrishna05 lets wait for another team member to review before merging

**Comment by nvamsikrishna05** [comment]
@samukweku sure. Thanks

**Comment by ericmjl** [comment]
@nvamsikrishna05, thank you for the contribution, and @samukweku thank you for reviewing the PR! I looked at it and I approve too. Going to hit merge.

**Pull request merged**
