### PR TITLE
[DEPR] deprecate `pivot_wider`

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- deprecate `pivot_wider` in favor of pandas pivot
- minor edits to `pivot_longer`

**This PR relates to #1045 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1263--pyjanitor.netlify.app

**Review by ericmjl — APPROVED** [review]
LGTM!

**Comment by fkgruber** [comment]
Too bad you are deprecating pivot_wider. Seems like a better useful function. What is the most efficient way to use pivot to get the same outputs pivot_wider? Because by default you get multi-index which are very inconvenient

**Comment by samukweku** [comment]
Hi @fkgruber kindly share an example you have and I can show how to deal with it. There is also the collapse_levels function to handle multiindex. We would like to not duplicate existing pandas functions. Open to suggestions/feedback. Thanks

**Comment by samukweku** [comment]
@ericmjl @fkgruber I'll write up a series of examples on the alternatives for the deprecated functions on [here](https://pyjanitor-devs.github.io/pyjanitor-examples/). Thoughts ?

**Comment by fkgruber** [comment]
Here is an example in R. Would love to see the equivalent in pyjanitor using non-deprecated functions
```
library(tidyverse)
mtcars %>% 
  rownames_to_column() %>%
  group_by(cyl) %>%
  summarise(mean=mean(mpg))%>%
  pivot_wider(names_from = cyl, values_from = mean)%>%
  mutate(Average= mean(c(`6`, `4`, `8`)),
         Diff_4= `4`-Average)
```

**Comment by samukweku** [comment]
@fkgruber this is a similar approach in pandas
```
import pandas as pd
url='https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv'
mtcars = pd.read_csv(url)
(mtcars
.groupby('cyl', as_index=False)
.agg(mean=('mpg','mean'))
.assign(index=1)
.pivot(index='index', columns='cyl',values='mean')
.rename_axis(columns=None,index=None)
.assign(Average=lambda df: df.mean(axis='columns'), 
        Diff_4= lambda df: df[4] - df.Average)
.round(2)
)
```

**Comment by fkgruber** [comment]
Thanks, 
so with pure pandas the pivot_wider provided in R becoes 3 calls
.assign(index=1)
.pivot(index='index', columns='cyl',values='mean')
.rename_axis(columns=None,index=None)
(by the way I have seen examples where .rename_axis(columns=None,index=None) does not work so it is not a general solution)

With janitor and pivot_wider we could do:

```
(mtcars
 .groupby('cyl', as_index=False)
 .agg(mean=('mpg','mean'))
 .assign(index=1)
 .pivot_wider(index="index",names_from='cyl', values_from='mean')
 .assign(Average=lambda df: df.mean(axis='columns'),
         Diff_4= lambda df: df[4] - df.Average)
)
```

And if pivot_wider would take of the index as dplyr does, then it would almost be the same number of lines as in R.

Seems like pivot_wider is helpful by reducing extra coding

**Comment by samukweku** [comment]
Kindly share an example where rename_axis does not work. We could raise an issue with the pandas team. The `assign(index=1)` is not required in all cases; tidyverse does not assign the same level of importance that pandas does to index.

Pandas pivot already does a great job and there is no need to repeat it; if there are edge cases it can be handled (happy to be proven wrong). Pandas does not have pivot_wider_spec or something close to it; pyjanitor has that. 

If you have any other scenario where pivot is not sufficient happy to work through it with you

**Comment by derekpowell** [comment]
I know this is closed, but I agree that `pivot_wider` seems like a helpful function for avoiding multi-index troubles, and for offering a direct like-for-like way of reversing a `pivot_longer`. Here's a simple case where dealing with a multi-index seems annoying.

```python
raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
            'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Corne'], 
            'female': [0, 1, 1, 0, 1],
            'age': [42, 52, 36, 24, 73], 
            'preTestScore': [4, 24, 31, 2, 3],
            'postTestScore': [25, 94, 57, 62, 70]}

df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'female', 'preTestScore', 'postTestScore'])

## create a long version
dfl = df.melt(
    id_vars = df.columns[~df.columns.isin(df.loc[: , 'preTestScore':'postTestScore'].columns)],
    value_vars = df.loc[: , 'preTestScore':'postTestScore']
)

## pivot back to wide
# ugly multi-index
dfw1 = dfl.pivot(index = ['first_name', 'last_name', 'age' ,'female'], columns = 'variable')

# nice and clean, matches df
dfw2 = dfl.pivot_wider(index = ['first_name', 'last_name', 'age' ,'female'], names_from = 'variable', values_from = 'value')
```

Attempting to clean up the index with `dfw1.reset_index().rename_axis(columns=None)` produces `TypeError: Must pass list-like as `names`.`

Apologies if there's a simpler fix I'm not seeing, but I can't seem to fix this without a fair few extra lines of code outside the pipe. 

Thanks for your consideration!

**Comment by samukweku** [comment]
@fkgruber @derekpowell thanks for your feedbacks on `pivot_wider`. We can undeprecate `pivot_wider`; I would love some feedback from the rest of the team on this - @pyjanitor-devs/core-devs @ericmjl. opinions?

**Comment by samukweku** [comment]
@derekpowell your `melt` can be simpler with `pivot_longer`: 
``` df.pivot_longer(column_names='*Score')```

**Comment by samukweku** [comment]
@derekpowell if you are interested, do you mind creating a PR that undeprecates pivot_wider?

**Comment by ericmjl** [comment]
@samukweku @derekpowell I'm a believer in listening to users, and it looks like this is one place where we can flex on pyjanitor's API policy (which is generally to not duplicate the pandas API), especially given the feedback. I'm in favor of un-deprecating it, that's not a problem.

**Comment by derekpowell** [comment]
@samukweku  @ericmjl I opened issue #1464 and PR #1465. There are some failing tests to follow up on potentially, being new to the project I wasn't able to run down the issues easily.

Thanks all for your openness!

**Pull request merged**
