### PR TITLE
[ENH] add `softmax` to `math` module

### LINKED ISSUE #902: [ENH] Add `softmax` to math submodule
In reviewing the `math` module, I'd like to add `softmax` to the functions. This will complete the "activation" functions :) as we have sigmoids but no softmax.

### PR DESCRIPTION
**Pull request by loganthomas**
# PR Description

Please describe the changes proposed in the pull request:

- This PR adds `softmax` to the `math` module

**This PR resolves #902**

# PR Checklist
Please ensure that you have done the following:

1. [X] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.
2. [X] If you're not on the contributors list, add yourself to `AUTHORS.rst`.
3. [X] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Review by ericmjl — APPROVED** [review]

**Review by ericmjl — APPROVED** [review]
Approving ahead-of-time. I think there is a test that is failing. Let me check the git blame to see whom we should ping about the test.

**Comment by ericmjl** [comment]
Tag @samukweku, I think we're getting errors on `test_dual_conditions_ne_and_eq`. Could I ask if you could help here please?

**Review by samukweku — APPROVED** [review]

**Comment by samukweku** [comment]
@loganthomas @ericmjl Upon rerun the error doesnt pop up. I need to rework the logic for conditional_join and address the error issue. Something that is a bit more convenient and easier to wrap the head around (for me at least :grin: ). I'll find time to get to it.

**Comment by loganthomas** [comment]
Thanks @samukweku!

@ericmjl Just curious what is causing codecov to complain. I think my PR is `100%` covered. Why would it fail if that is the case?

**Comment by ericmjl** [comment]
@loganthomas codecov has been finnicky lately. Let's keep monitoring it, might be an issue with their cache of metrics, possibly.

**Pull request merged**
