### PR TITLE
[DOC] MkDocs Chemistry

### PR DESCRIPTION
**Pull request by ericmjl**
This PR is for docstring changes to the chemistry submodule.

### CODE REVIEW

**Comment by ericmjl** [comment]
@samukweku, @loganthomas & @nvamsikrishna05 this is an example for you all!

May I ask that you guys approve the PR when you're done reviewing it, and whoever is the last do the honors of merging (if the tests all pass)?

**Review by loganthomas — APPROVED** [review]
Awesome. Thanks @ericmjl  I'm assuming that we can build locally via `mkdocs serve`?

**Comment by ericmjl** [comment]
Yes, that is right, as long as you have `mkdocs` installed in your dev environment!

**Comment by loganthomas** [comment]
> Yes, that is right, as long as you have `mkdocs` installed in your dev environment!

+   `mkdocs-material` `mkdocstrings`

**Comment by loganthomas** [comment]
> Yes, that is right, as long as you have `mkdocs` installed in your dev environment!

`mkdocs-material` `mkdocstrings`

**Pull request merged**
