### PR TITLE
[DOC] Fix typos

### LINKED ISSUE #1291: Typos in repository
# Brief Description of Fix

Typos found by `codespell`:

```sh
./nbconvert_config.py:272: informations ==> information
./nbconvert_config.py:433: usefull ==> useful
./CONTRIBUTING.md:38: shouln't ==> shouldn't
./CONTRIBUTING.md:156: environemnt ==> environment
./CONTRIBUTING.md:168: commited ==> committed
./CONTRIBUTING.md:191: continous ==> continuous
./examples/convert_currency.md:16: ZAR ==> CZAR
./examples/convert_currency.md:21: ZAR ==> CZAR
./examples/notebooks/french_trains.ipynb:13: ressources ==> resources
./examples/notebooks/french_trains.ipynb:451: yOT ==> yacht
./examples/notebooks/french_trains.ipynb:451: bU ==> by, be, but, bug, bun, bud, buy, bum
./examples/notebooks/french_trains.ipynb:451: Fo ==> Of, For, To, Do, Go
./examples/notebooks/normalize.ipynb:329: TJE ==> THE
./examples/notebooks/dirty_data.ipynb:711: certifiation ==> certification
./examples/notebooks/medium_franchise.ipynb:18: seperate ==> separate
./examples/notebooks/medium_franchise.ipynb:69: Supress ==> Suppress
./examples/notebooks/medium_franchise.ipynb:223: patten ==> pattern, patent
./examples/notebooks/medium_franchise.ipynb:598: splitted ==> split
./examples/notebooks/medium_franchise.ipynb:745: licens ==> license
./examples/notebooks/medium_franchise.ipynb:891: licens ==> license
./examples/notebooks/board_games.ipynb:941: reccomended ==> recommended
./examples/notebooks/board_games.ipynb:951: ONL ==> ONLY
./examples/notebooks/anime.ipynb:58: Supress ==> Suppress
./examples/notebooks/anime.ipynb:1319: optinal ==> optional
./examples/notebooks/Pivoting Data from Wide to Long.ipynb:3567: infact ==> in fact
./janitor/finance.py:48: ZAR ==> CZAR
./janitor/finance.py:85: CAF ==> CALF
./janitor/finance.py:129: FRO ==> FOR, FROM
./janitor/finance.py:222: NAM ==> NAME
./janitor/finance.py:264: SOM ==> SOME
./janitor/finance.py:284: THA ==> THAN, THAT, THE
./janitor/finance.py:468: ZAR ==> CZAR
./janitor/finance.py:474: ZAR ==> CZAR
./janitor/functions/factorize_columns.py:20: overriden ==> overridden
./janitor/functions/conditional_join.py:801: possiblity ==> possibility
./janitor/functions/complete.py:329: wil ==> will, well
./mkdocs/devguide.md:38: shouln't ==> shouldn't
./mkdocs/devguide.md:156: environemnt ==> environment
./mkdocs/devguide.md:168: commited ==> committed
./mkdocs/devguide.md:191: continous ==> continuous
./tests/functions/test_encode_categorical.py:90: regon ==> region
./tests/functions/test_pivot_wider.py:99: variabl ==> variable
./tests/functions/test_pivot_wider.py:115: variabl ==> variable
./tests/functions/test_pivot_wider.py:220: doesnt ==> doesn't, does not
./tests/functions/test_coalesce.py:59: ouptut ==> output
./tests/functions/test_select_columns.py:385: columnns ==> columns
./tests/functions/test_select_columns.py:393: mapp ==> map
./tests/functions/test_select_columns.py:394: mapp ==> map
./tests/functions/test_select_columns.py:401: mapp ==> map
./tests/functions/test_select_columns.py:402: mapp ==> map
./tests/functions/test_select_columns.py:409: mapp ==> map
./tests/functions/test_select_columns.py:410: mapp ==> map
./tests/functions/test_select_columns.py:417: mapp ==> map
./tests/functions/test_select_columns.py:418: mapp ==> map
./tests/functions/test_select_columns.py:425: mapp ==> map
./tests/functions/test_select_columns.py:426: mapp ==> map
./tests/functions/test_select_rows.py:212: mapp ==> map
./tests/functions/test_select_rows.py:213: mapp ==> map
./tests/functions/test_sort_column_value_order.py:17: equivilent ==> equivalent
./tests/test_data/corrected_smiles.txt:148: Te ==> The, Be, We, To
./tests/test_data/sequences.tsv:807: Nam ==> Name
./tests/test_data/sequences.tsv:808: Nam ==> Name
./tests/test_data/sequences.tsv:809: Bage ==> Bag
./tests/test_data/sequences.tsv:810: Bage ==> Bag
./tests/test_data/sequences.tsv:811: Bage ==> Bag
./tests/test_data/sequences.tsv:3243: Nam ==> Name
./tests/test_data/sequences.tsv:3244: Nam ==> Name
./tests/test_data/sequences.tsv:3245: Nam ==> Name
./tests/test_data/sequences.tsv:3720: Nam ==> Name
./tests/test_data/sequences.tsv:3721: Nam ==> Name
./tests/test_data/sequences.tsv:3728: Nam ==> Name
./tests/test_data/sequences.tsv:3729: Nam ==> Name
./tests/test_data/sequences.tsv:3730: Nam ==> Name
./tests/test_data/sequences.tsv:3731: Nam ==> Name
./tests/test_data/sequences.tsv:3732: Nam ==> Name
./tests/test_data/sequences.tsv:3846: Nam ==> Name
./tests/test_data/sequences.tsv:4548: Nam ==> Name
./tests/test_data/sequences.tsv:4549: Nam ==> Name
./tests/test_data/sequences.tsv:4550: Nam ==> Name
./tests/test_data/sequences.tsv:4551: Nam ==> Name
./tests/test_data/sequences.tsv:4552: Nam ==> Name
./tests/test_data/sequences.tsv:4553: Nam ==> Name
./tests/test_data/sequences.tsv:4554: Nam ==> Name
./tests/test_data/sequences.tsv:4555: Nam ==> Name
./tests/test_data/sequences.tsv:4556: Nam ==> Name
./tests/test_data/sequences.tsv:4557: Nam ==> Name
./tests/test_data/sequences.tsv:4558: Nam ==> Name
./tests/test_data/sequences.tsv:4559: Nam ==> Name
./tests/test_data/sequences.tsv:4560: Nam ==> Name
./tests/test_data/sequences.tsv:4561: Nam ==> Name
./tests/test_data/sequences.tsv:4562: Nam ==> Name
./tests/test_data/sequences.tsv:4563: Nam ==> Name
./tests/test_data/sequences.tsv:4564: Nam ==> Name
./tests/test_data/sequences.tsv:4565: Nam ==> Name
./tests/test_data/sequences.tsv:4566: Nam ==> Name
./tests/test_data/sequences.tsv:4567: Nam ==> Name
./tests/test_data/sequences.tsv:4568: Nam ==> Name
./tests/test_data/sequences.tsv:4569: Nam ==> Name
./tests/test_data/sequences.tsv:4570: Nam ==> Name
./tests/test_data/sequences.tsv:4571: Nam ==> Name
./tests/test_data/sequences.tsv:4572: Nam ==> Name
./tests/test_data/sequences.tsv:4573: Nam ==> Name
./tests/test_data/sequences.tsv:4574: Nam ==> Name
./tests/test_data/sequences.tsv:4575: Nam ==> Name
./tests/test_data/sequences.tsv:4576: Nam ==> Name
./tests/test_data/sequences.tsv:4577: Nam ==> Name
./tests/test_data/sequences.tsv:4578: Nam ==> Name
./tests/test_data/sequences.tsv:4579: Nam ==> Name
./tests/test_data/sequences.tsv:4580: Nam ==> Name
./tests/test_data/sequences.tsv:4581: Nam ==> Name
./tests/test_data/sequences.tsv:4582: Nam ==> Name
./tests/test_data/sequences.tsv:4583: Nam ==> Name
./tests/test_data/sequences.tsv:4584: Nam ==> Name
./tests/test_data/sequences.tsv:4585: Nam ==> Name
./tests/test_data/sequences.tsv:4586: Nam ==> Name
./tests/test_data/sequences.tsv:4587: Nam ==> Name
./tests/test_data/sequences.tsv:4588: Nam ==> Name
./tests/test_data/sequences.tsv:4589: Nam ==> Name
./tests/test_data/sequences.tsv:4590: Nam ==> Name
./tests/test_data/sequences.tsv:4591: Nam ==> Name
./tests/test_data/sequences.tsv:4592: Nam ==> Name
./tests/test_data/sequences.tsv:4593: Nam ==> Name
./tests/test_data/sequences.tsv:4594: Nam ==> Name
./tests/test_data/sequences.tsv:4595: Nam ==> Name
./tests/test_data/sequences.tsv:4596: Nam ==> Name
./tests/test_data/sequences.tsv:4597: Nam ==> Name
./tests/test_data/sequences.tsv:4598: Nam ==> Name
./tests/test_data/sequences.tsv:4599: Nam ==> Name
./tests/test_data/sequences.tsv:4600: Nam ==> Name
./tests/test_data/sequences.tsv:4601: Nam ==> Name
./tests/test_data/sequences.tsv:4602: Nam ==> Name
./tests/test_data/sequences.tsv:4603: Nam ==> Name
./tests/test_data/sequences.tsv:4604: Nam ==> Name
./tests/test_data/sequences.tsv:4605: Nam ==> Name
./tests/test_data/sequences.tsv:4606: Nam ==> Name
./tests/test_data/sequences.tsv:4607: Nam ==> Name
./tests/test_data/sequences.tsv:4608: Nam ==> Name
./tests/test_data/sequences.tsv:4609: Nam ==> Name
./tests/test_data/sequences.tsv:4610: Nam ==> Name
./tests/test_data/sequences.tsv:4611: Nam ==> Name
./tests/test_data/sequences.tsv:4612: Nam ==> Name
./tests/test_data/sequences.tsv:4613: Nam ==> Name
./tests/test_data/sequences.tsv:4614: Nam ==> Name
./tests/test_data/sequences.tsv:4615: Nam ==> Name
./tests/test_data/sequences.tsv:4616: Nam ==> Name
./tests/test_data/sequences.tsv:4617: Nam ==> Name
./tests/test_data/sequences.tsv:4618: Nam ==> Name
./tests/test_data/sequences.tsv:4619: Nam ==> Name
./tests/test_data/sequences.tsv:4620: Nam ==> Name
./tests/test_data/sequences.tsv:4621: Nam ==> Name
./tests/test_data/sequences.tsv:4622: Nam ==> Name
./tests/test_data/sequences.tsv:4623: Nam ==> Name
./tests/test_data/sequences.tsv:4624: Nam ==> Name
./tests/test_data/sequences.tsv:4625: Nam ==> Name
./tests/test_data/sequences.tsv:4626: Nam ==> Name
./tests/test_data/sequences.tsv:4627: Nam ==> Name
./tests/test_data/sequences.tsv:4628: Nam ==> Name
./tests/test_data/sequences.tsv:4629: Nam ==> Name
./tests/test_data/sequences.tsv:4630: Nam ==> Name
./tests/test_data/sequences.tsv:4631: Nam ==> Name
./tests/test_data/sequences.tsv:4632: Nam ==> Name
./tests/test_data/sequences.tsv:4633: Nam ==> Name
./tests/test_data/sequences.tsv:4634: Nam ==> Name
./tests/test_data/sequences.tsv:4635: Nam ==> Name
./tests/test_data/sequences.tsv:4636: Nam ==> Name
./tests/test_data/sequences.tsv:4637: Nam ==> Name
./tests/test_data/sequences.tsv:4638: Nam ==> Name
./tests/test_data/sequences.tsv:4639: Nam ==> Name
./tests/test_data/sequences.tsv:4640: Nam ==> Name
./tests/test_data/sequences.tsv:4901: Nam ==> Name
./tests/test_data/sequences.tsv:4902: Nam ==> Name
./tests/test_data/sequences.tsv:4903: Nam ==> Name
./tests/test_data/sequences.tsv:4904: Nam ==> Name
./tests/test_data/sequences.tsv:4905: Nam ==> Name
./tests/test_data/sequences.tsv:4906: Nam ==> Name
./tests/test_data/sequences.tsv:4907: Nam ==> Name
./tests/test_data/sequences.tsv:4908: Nam ==> Name
./tests/test_data/sequences.tsv:4909: Nam ==> Name
./tests/test_data/sequences.tsv:4910: Nam ==> Name
./tests/test_data/sequences.tsv:4911: Nam ==> Name
./tests/test_data/sequences.tsv:4912: Nam ==> Name
./tests/test_data/sequences.tsv:4913: Nam ==> Name
./tests/test_data/sequences.tsv:4914: Nam ==> Name
./tests/test_data/sequences.tsv:4915: Nam ==> Name
./tests/test_data/sequences.tsv:4916: Nam ==> Name
./tests/test_data/sequences.tsv:4917: Nam ==> Name
./tests/test_data/sequences.tsv:4918: Nam ==> Name
./tests/test_data/sequences.tsv:4919: Nam ==> Name
./tests/test_data/sequences.tsv:4920: Nam ==> Name
./tests/test_data/sequences.tsv:4921: Nam ==> Name
./tests/test_data/sequences.tsv:4922: Nam ==> Name
./tests/test_data/sequences.tsv:4923: Nam ==> Name
./tests/test_data/sequences.tsv:5411: Nam ==> Name
./tests/test_data/sequences.tsv:5412: Nam ==> Name
./tests/test_data/sequences.tsv:5413: Nam ==> Name
./tests/test_data/sequences.tsv:5414: Nam ==> Name
./tests/test_data/sequences.tsv:5415: Nam ==> Name
./tests/test_data/sequences.tsv:5416: Nam ==> Name
./tests/test_data/sequences.tsv:5417: Nam ==> Name
./tests/test_data/sequences.tsv:5418: Nam ==> Name
./tests/test_data/sequences.tsv:5421: Nam ==> Name
./tests/test_data/sequences.tsv:5422: Nam ==> Name
./tests/test_data/sequences.tsv:5423: Nam ==> Name
./tests/test_data/sequences.tsv:6420: Nam ==> Name
./tests/test_data/sequences.tsv:6421: Nam ==> Name
./tests/test_data/sequences.tsv:6422: Nam ==> Name
./tests/test_data/sequences.tsv:6423: Nam ==> Name
./tests/test_data/sequences.tsv:6424: Nam ==> Name
./tests/test_data/sequences.tsv:6425: Nam ==> Name
./tests/test_data/sequences.tsv:6485: Nam ==> Name
./tests/test_data/sequences.tsv:6486: Nam ==> Name
./tests/test_data/sequences.tsv:6487: Nam ==> Name
./tests/test_data/sequences.tsv:7936: Nam ==> Name
./tests/test_data/sequences.tsv:7937: Nam ==> Name
./tests/test_data/sequences.tsv:7938: Nam ==> Name
./tests/test_data/sequences.tsv:7939: Nam ==> Name
./tests/test_data/sequences.tsv:7946: Nam ==> Name
./tests/test_data/sequences.tsv:12368: Nam ==> Name
./tests/test_data/sequences.tsv:12369: Nam ==> Name
./tests/test_data/sequences.tsv:12370: Nam ==> Name
./tests/test_data/sequences.tsv:12371: Nam ==> Name
./tests/test_data/sequences.tsv:12372: Nam ==> Name
./tests/test_data/sequences.tsv:12373: Nam ==> Name
./tests/test_data/sequences.tsv:12503: Nam ==> Name
./tests/test_data/sequences.tsv:12504: Nam ==> Name
./tests/test_data/sequences.tsv:14526: Nam ==> Name
./tests/test_data/sequences.tsv:14527: Nam ==> Name
./tests/test_data/sequences.tsv:14528: Nam ==> Name
./tests/test_data/sequences.tsv:14529: Nam ==> Name
./tests/test_data/sequences.tsv:14530: Nam ==> Name
./tests/test_data/sequences.tsv:14531: Nam ==> Name
./tests/test_data/sequences.tsv:14532: Nam ==> Name
./tests/test_data/sequences.tsv:14533: Nam ==> Name
./tests/test_data/sequences.tsv:14534: Nam ==> Name
./tests/test_data/sequences.tsv:14535: Nam ==> Name
./tests/test_data/sequences.tsv:14536: Nam ==> Name
./tests/test_data/sequences.tsv:14537: Nam ==> Name
./tests/test_data/sequences.tsv:14538: Nam ==> Name
./tests/test_data/sequences.tsv:14539: Nam ==> Name
./tests/test_data/sequences.tsv:14540: Nam ==> Name
./tests/test_data/sequences.tsv:14541: Nam ==> Name
./tests/test_data/sequences.tsv:14542: Nam ==> Name
./tests/test_data/sequences.tsv:14543: Nam ==> Name
./tests/test_data/sequences.tsv:14544: Nam ==> Name
./tests/test_data/sequences.tsv:14545: Nam ==> Name
./tests/test_data/sequences.tsv:14546: Nam ==> Name
./tests/test_data/sequences.tsv:14547: Nam ==> Name
./tests/test_data/sequences.tsv:14548: Nam ==> Name
./tests/test_data/sequences.tsv:14549: Nam ==> Name
./tests/test_data/sequences.tsv:14550: Nam ==> Name
./tests/test_data/sequences.tsv:14551: Nam ==> Name
./tests/test_data/sequences.tsv:14552: Nam ==> Name
./tests/test_data/sequences.tsv:14553: Nam ==> Name
./tests/test_data/sequences.tsv:14554: Nam ==> Name
./tests/test_data/sequences.tsv:14555: Nam ==> Name
./tests/test_data/sequences.tsv:14556: Nam ==> Name
./tests/test_data/sequences.tsv:14557: Nam ==> Name
./tests/test_data/sequences.tsv:14558: Nam ==> Name
./tests/test_data/sequences.tsv:14559: Nam ==> Name
./tests/math/test_probit.py:12: ans ==> and
./tests/math/test_probit.py:21: ans ==> and
./tests/math/test_probit.py:28: ans ==> and
./tests/math/test_logit.py:11: ans ==> and
./tests/math/test_logit.py:20: ans ==> and
./tests/math/test_logit.py:27: ans ==> and
./tests/math/test_z_score.py:12: ans ==> and
./tests/math/test_z_score.py:16: ans ==> and
```

### PR DESCRIPTION
**Pull request by kianmeng**
# PR Description

Fix typos found via `codespell -L
nam,ans,bage,te,mapp,zar,caf,fro,som,tha,tje,yot,bu,fo,ressources,onl,regon,licens,variabl`

**This PR resolves #1291 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by samukweku** [comment]
hi @kianmeng and thank you for the PR. do you mind creating an issue, so we can reference this PR from there? thanks

**Comment by kianmeng** [comment]
@samukweku Done. https://github.com/pyjanitor-devs/pyjanitor/issues/1291

**Review by samukweku — APPROVED** [review]

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
@kianmeng that's pretty cool, I learned a new thing today!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
