### PR TITLE
[INF] Openpyxl env dep

### LINKED ISSUE #772: Add Openpyxl to list of libraries in the environment_dev.yml
xlrd is currently unmaintained, and causing some issues while reading an excel file in one of the tests (test_convert_excel_date.py). I propose adding `openpyxl` to the environment_dev, as it is a good alternative, can read xlsx files and is still maintained.

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Add `openpyxl` to environment_dev

**This PR resolves #772 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by hectormz** [comment]
@samukweku see my comments on #772 and #771, but I don't think this is the solution to our problems.

**Comment by hectormz** [comment]
@samukweku I don't think this should have been merged without deciding this was the best route to take. In group projects like this, I don't think it's a good idea to merge your own PRs (unless you are BDFL)

**Comment by ericmjl** [comment]
Thanks for the catch, @hectormz. Partially my responsibility, as I didn't delegate decision-making responsibilities properly either. Don't feel to bad about this one, @samukweku. If there's anything that needs to be reverted, another PR is good. Nothing "irreversible" with Git anyways; the releases are the main thing that we probably wanna be accountable for.

**Comment by samukweku** [comment]
@hectormz @ericmjl And the rest of the team. My apologies on this.

**Comment by hectormz** [comment]
@samukweku no worries, it's a small change. I just wanted to make sure we are reviewing everyone's PRs.

**Pull request merged**
