### PR TITLE
[BUGFIX]`coalesce`

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- ensure `get_index_labels` is called early in the code - column check, easy column selection ...

**This PR improves coalesce.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1325--pyjanitor.netlify.app

**Comment by samukweku** [comment]
@pyjanitor-devs/core-devs @ericmjl how do I check the minimum pandas version? in the tests, i can see pandas 1.3.5, whereas working in dev i see the minimum version is pandas 1.5.3

**Comment by ericmjl** [comment]
> @pyjanitor-devs/core-devs @ericmjl how do I check the minimum pandas version? in the tests, i can see pandas 1.3.5, whereas working in dev i see the minimum version is pandas 1.5.3

This is interesting, I need to check how the environments are built. Give me one moment, @samukweku!

**Comment by ericmjl** [comment]
@samukweku `environment-dev.yml` was pinned to 1.3.5. I'm not sure what the reason is, but we should release the pin and let it float with the ecosystem. I'm going to make a push.

**Comment by ericmjl** [comment]
@samukweku I'm not sure what's happening after releasing the version pin, but `pivot_wider`'s docstring examples appear to be failing. I made sure pytest skipped those tests, since we are going to be deprecating that function anyways.

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
Since I pushed to the PR, that means I've accepted the contents of it :smile:. Officially approving, and now going to merge! Thank you, @samukweku!

**Pull request merged**
