### PR TITLE
[ENH] Added truncation to clean_names

### LINKED ISSUE #753: Truncate long column names ?
# Brief Description

Often when exporting CSVs from questionnaires, the column names are paragraphs, or really long strings.

I would like to propose that we add an option to `clean_names` that truncates long sentence column names to something shorter. This would be useful not just in looking at the df in a notebook, but also when renaming it. Currently my workaround is to print the column names, and then use a dictionary with existing:new column names that gets passed into the rename column method.

# Example API

```python
cleaned_df = (
    pd.read_csv('data/Learning Log #1 Survey Student Analysis Report.csv')
    .clean_names(remove_special = True, truncate_limit = 50)
    .remove_empty()
)
```

^ the tuncate_limit can be defaulted to None to avoid truncating, and a number enables the maximum number of characters in the column.

### PR DESCRIPTION
**Pull request by richardqiu**
# PR Description

Please describe the changes proposed in the pull request:

- Addition of optional `truncate_limit` argument for `clean_names` as suggested in #753 

**This PR resolves #753.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [x] Ensure that you have added tests.
- [x] Run all tests (`$ pytest .`) locally on your machine.
    - [x] Check to ensure that test coverage covers the lines of code that you have added.
    - [x] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by richardqiu** [comment]
Not sure why `test__get_missing_timestamps` is failing, and only on MacOS. I don't think it's affected by my changes to `clean_names` and I'm not on MacOS, so I can't investigate locally.

**Review by samukweku — APPROVED** [review]
LGTM, pending fix from @UGuntupalli, regarding the ``get_missing_timestamps``` test fail.

**Review by ericmjl — APPROVED** [review]
I approve!

**Comment by ericmjl** [comment]
@samukweku use thy powers on the CI system! :smile:

**Comment by samukweku** [comment]
@ericmjl done! Super powers!

**Comment by ericmjl** [comment]
@richardqiu I think this is good to go. Not so worried about the minor change in coverage. Thanks!

**Pull request merged**
