### PR TITLE
[INF] Infra upgrades

### LINKED ISSUE #1236: [INF] darglint is archived -> move to ruff?
While working on #1235, I've experienced darglint to be really slow (takes minutes to run for the `functions/pivot.py` file), and also the project has been archived as of Dec 16 2022.

https://github.com/terrencepreilly/darglint/

We should transition to using `ruff`, which also provides darglint rules.

In which case, perhaps we can also drop `flake8` in favour of ruff.

EDIT:

oops, I misremembered. darglint is not covered by ruff yet, but it's in the works. https://github.com/charliermarsh/ruff/issues/458

### PR DESCRIPTION
**Pull request by ericmjl**
# PR Description

Please describe the changes proposed in the pull request:

- f773587 test: limit max examples in pytest settings to 10 for multiple test functions
- 4ee8593 test: limit max examples in pytest settings to 10
- 3675166 test: limit max examples in pytest settings to 10
- 0b1b27e Bump urllib3 from 1.26.14 to 1.26.17 in /.requirements (#1292)
- 6fbd040 refactor(janitor): reorganize function imports and remove unused imports
- f33a8ef test: import janitor in test_fill_direction.py
- db953a1 refactor(tests): import janitor module in test files
- 60ecd75 refactor(janitor/functions): remove unused imports and dynamic import function
- dfdc31a refactor: update dynamic_import argument and limit test examples
- 31428fd feat(janitor/functions): add dynamic import functionality
- 3055c9a feat(utils): add dynamic_import function and import janitor.chemistry in test
- 41199d4 test: remove redundant dataframe method registration tests
- 0259c8d refactor(janitor): update import statements and function usage
- f9a2cbb feat(janitor): add 'col' utility to functions
- 837c657 chore: remove darglint checks workflow
- 9f557d4 refactor: update docstrings and remove redundant comments
- 246badf refactor(janitor/utils): use isinstance for type checking
- 7da6a9d feat: update pre-commit hooks and add pydoclint
- c8fd19b chore: disable darglint in pre-commit config
- 96122f4 infra: satisfy the shiny new ruff linter
- 0f356e9 chore: Comment out darglint and add --fix arg to ruff
- 15009f6 chore(environment-dev): update Python and rdkit versions
- 83f48cb chore(pyproject.toml): Update target Python version to 3.10
- 7e9253f feat: Add ruff tool configuration to pyproject.toml
- 40a5f7e chore: update pre-commit hooks

**This PR resolves #1236.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl
- @samukweku 
- @thatlittleboy

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1294--pyjanitor.netlify.app

**Comment by ericmjl** [comment]
@thatlittleboy bang bang! 6.2 seconds for pre-commit hooks check 😄

**Comment by ericmjl** [comment]
Internal Server Error

**Comment by samukweku** [comment]
Ruff supports darglint? That's fantastic

**Comment by ericmjl** [comment]
Not yet! But there is a replacement for it, `pydoclint`, which I learned about from the associated issue tracker on Ruff.

- Pydoclint: https://github.com/jsh9/pydoclint
- Relevant ruff issue: https://github.com/astral-sh/ruff/issues/458

**Comment by samukweku** [comment]
More power to open source

**Comment by ericmjl** [comment]
@samukweku I think we're good to go here! The patch target is lower, but at least we've got the project coverage up.

**Comment by ericmjl** [comment]
@samukweku I did one other thing to speed up the turtle tests: we only run 10 examples now, rather than the usual 100. That should substantially cut down on the iteration time needed to get feedback on the CI system

**Comment by ericmjl** [comment]
I guess in general, if a Hypothesis-based test takes >1 second to run, we should drop the max number of examples on that test to 10.

**Comment by ericmjl** [comment]
Okie dokes, everyone, ready for review. Most of the changes don't need to be reviewed, I think (it's just a matter of taking test times down by reducing the number of examples Hypothesis generates), but the others that are infrastructure-related, particularly:

- darglint -> pydoclint
- flake8 and others -> ruff

are ready for review.

Tagging @thatlittleboy @Zeroto521 and @samukweku for review please!

**Review by samukweku — APPROVED** [review]

**Pull request merged**
