### PR TITLE
Pivot_longer Refactor

### PR DESCRIPTION
**Pull request by samukweku**
-->

# PR Description

Please describe the changes proposed in the pull request:

- Removed `pd.to_numeric` function
- Added `dtypes` argument, allowing user to control data type of columns
- Use `pd.DataFrame.stack` method instead, as it is easier to manipulate from, and
- also ensure a one-to-one mapping of extraction to source data in the columns. Also helps 
- to achieve order of appearance w.r.t to the source data columns; user can choose to sort data afterwards.
- Allow explicit exposure of mising variables in final dataframe.
- Refactored code to make it simpler and more maintainable.

**This PR improves #755 **

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [x] Ensure that you have added tests.
- [x] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by samukweku** [comment]
@ericmjl , @loganthomas @szuckerman  I need guidance here on how to resolve the codecov decrease

**Comment by samukweku** [comment]
@ericmjl , if you have some time, can you point me to the lines of code that is decreasing the coverage?

**Comment by ericmjl** [comment]
@samukweku I think we're good here. I can't seem to pinpoint where code coverage went down either, so let's merge it after resolving the conflicts.

**Review by ericmjl — APPROVED** [review]
Many apologies! I realized I forgot to approve after my last comment. Let's merge when you're ready!

**Comment by ericmjl** [comment]
Thanks @samukweku!

**Pull request merged**
