### PR TITLE
refactor: remove lazy_loader dependency

### PR DESCRIPTION
**Pull request by ericmjl**
# PR Description

This PR removes the dependency on lazy_loader across the codebase. The changes include:
- Removing lazy_loader from the requirements and environment files.
- Refactoring the import statements in various files to directly import the required modules instead of using lazy_loader.
- Updating the docstrings to reflect the changes in the import statements.

This change simplifies the codebase and makes it easier to understand and maintain.
It also reduces the number of dependencies, which can help to reduce potential issues related to dependency management.
Finally, by getting rid of lazy_loader, we should encounter fewer errors.

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @samukweku
- @thatlittleboy

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1278--pyjanitor.netlify.app

**Review by samukweku — APPROVED** [review]

**Comment by samukweku** [comment]
@ericmjl I'm guessing we are taking the same action with `pandas_flavor` - getting rid of lazy loading?

**Comment by ericmjl** [comment]
Yep, that's right, @samukweku! Already done and released :smile:.

**Comment by samukweku** [comment]
Cool. If no updates, I can merge this

**Comment by ericmjl** [comment]
Let's make sure the test coverage isn't broken first, though. If we're hovering around 96% that's not an issue, but I saw 83% coverage on the project.

**Comment by ericmjl** [comment]
@samukweku I just checked up on this PR; I think we can merge soon!

**Comment by ericmjl** [comment]
@samukweku I see we've only got a small patch diff issue, but code coverage goes up anyways. Let's merge?

**Comment by samukweku** [comment]
I think so, yes

**Pull request merged**
