### PR TITLE
docstring update

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- docstrings cleanup for `fill_direction`, `fill_empty`, `update_where`

**This PR relates to #972 .**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1100--pyjanitor.netlify.app

**Comment by samukweku** [comment]
@ericmjl / @thatlittleboy @pyjanitor-devs/core-devs pls what am I missing regarding the docs build; the preview is not changing to reflect the latest updates

**Comment by thatlittleboy** [comment]
> @ericmjl / @thatlittleboy @pyjanitor-devs/core-devs pls what am I missing regarding the docs build; the preview is not changing to reflect the latest updates

@samukweku The link for this PR https://deploy-preview-1100--pyjanitor.netlify.app/ contains the latest updates as far as I can see.

image

**Review by thatlittleboy — APPROVED** [review]
Thanks!

**Comment by samukweku** [comment]
thanks @thatlittleboy the issue is from my end then!

**Review by ericmjl — APPROVED** [review]
Approving! It's a nice and small and self-contained update. Thank you, @samukweku!

**Comment by ericmjl** [comment]
We don't have to worry about codecov, it's being wonky again lol.

**Comment by samukweku** [comment]
> Approving! It's a nice and small and self-contained update. Thank you, @samukweku!

I'll keep this in mind going forward 😀

**Pull request merged**
