### PR TITLE
[ENH] fix bug pivot_longer

### LINKED ISSUE #827: [bug] pivot_longer fails when number of entries differ for '.value'
# Brief Description

When pivoting to long form, with `.value`, it is expected that the sub structures will be dataframes. This is not the case all the time, and raises an error.

# System Information

- Operating system: Linux
- OS details (optional):  Linux
- Python version (required): 3.9

# Minimally Reproducible Code

```python

df = [{'x1': 4, 'y1': 7}, {'x1': 5, 'y1': 8}, {'x1': 6, 'y1': 9}]

df

   x1  y1
0   4   7
1   5   8
2   6   9


df.pivot_longer(names_to=".value", names_pattern = r"(.).")
```

# Error Messages

```
AttributeError                            Traceback (most recent call last)
<ipython-input-147-7afe0417624a> in <module>
----> 1 df.pivot_longer(names_to=".value", names_pattern = r"(.).")

~/miniforge3/envs/datatable/lib/python3.9/site-packages/pandas_flavor/register.py in __call__(self, *args, **kwargs)
     27             @wraps(method)
     28             def __call__(self, *args, **kwargs):
---> 29                 return method(self._obj, *args, **kwargs)
     30 
     31         register_dataframe_accessor(method.__name__)(AccessorMethod)

~/miniforge3/envs/datatable/lib/python3.9/site-packages/janitor/functions.py in pivot_longer(df, index, column_names, names_to, values_to, column_level, names_sep, names_pattern, sort_by_appearance, ignore_index)
   5744     )
   5745 
-> 5746     df = _computations_pivot_longer(
   5747         df,
   5748         index,

~/miniforge3/envs/datatable/lib/python3.9/site-packages/janitor/utils.py in _computations_pivot_longer(df, index, column_names, names_to, values_to, column_level, names_sep, names_pattern, sort_by_appearance, ignore_index)
   1522     else:  # .value
   1523         if df_columns.nlevels == 1:
-> 1524             df = [
   1525                 df[name].melt(ignore_index=False)
   1526                 # changing the name in `rename`

~/miniforge3/envs/datatable/lib/python3.9/site-packages/janitor/utils.py in <listcomp>(.0)
   1523         if df_columns.nlevels == 1:
   1524             df = [
-> 1525                 df[name].melt(ignore_index=False)
   1526                 # changing the name in `rename`
   1527                 # instead of passing it to `melt`

~/miniforge3/envs/datatable/lib/python3.9/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5463             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5464                 return self[name]
-> 5465             return object.__getattribute__(self, name)
   5466 
   5467     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'melt'

```

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- fix bug where sub structures are series, not dataframes, preventing melt from occuring.

**This PR resolves #827.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by samukweku** [comment]
the test error is from janitors/finance.py. It seems the url is not working anymore, and one may have to register on the site to get api keys. Not sure what the alternative is;

**Comment by ericmjl** [comment]
@samukweku I triggered a test re-run. Let's see what happens.

**Comment by ericmjl** [comment]
@samukweku looks like the tests are still failing.

Good digging before on this - if indeed we need an API key to do currency conversions, then it's going to be challenging for users and for us. We might need to either:

1. Find a different service, or 
2. Deprecate the finance APIs.

For now, I don't want this to be a blocker for you. Could you mark the tests as xfail and let's get the bug fix in first? Also, can you add in a comment that references my response, so we have context on why it's marked xfail?

**Comment by samukweku** [comment]
@ericmjl, there is a notebook for currency conversion that also fails, since it is based on the API?

**Comment by ericmjl** [comment]
Looks like that one will also have to be taken offline. Can you disable them in the sphinx configuration file? There should be a `conf.py`. I found [the docs](https://nbsphinx.readthedocs.io/en/0.8.2/); the info in there should give you a headstart!

**Comment by samukweku** [comment]
@ericmjl I think I'm missing something regarding the conf.py/individual notebook execution stop; if you have an idea i'll gladly take that and resolve this. [explicitly disable jupyter notebook execution](https://nbsphinx.readthedocs.io/en/0.8.3/never-execute.html)

**Comment by ericmjl** [comment]
@samukweku I just pushed a small change to `conf.py`. Let's see if that fixes the problem.

**Comment by ericmjl** [comment]
@samukweku I went back and forth on what would be the best way to resolve this issue. The best way is to look for a new exchange rates API, while disabling the function so that we can retain the state of "all tests passing". We can invite users to help us find a new API that we can hit.

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
@anzelpwj and @zjpoh, sorry to bother you two here, but I'm struggling to figure out why the spark session thingy is failing. Would either of you be kind enough to help out here?

**Comment by jk3587** [comment]
nit: I suggest we change the error to say we "call" the api instead of "hit" (or anything other than "hit").

**Comment by ericmjl** [comment]
@jk3587 good _call_ on that one (\*cough cough\*) 😃. I will change that.

**Comment by ericmjl** [comment]
Oh my, we're finally done here!

**Comment by ericmjl** [comment]
@samukweku going to merge now.

**Pull request merged**
