### PR TITLE
[INF] Switching from Azure Pipelines to GitHub Actions

### PR DESCRIPTION
**Pull request by ericmjl**
# PR Description

Please describe the changes proposed in the pull request:

- Switched off Azure Pipelines
- Switched on GitHub actions
- Parallelized the checks for speed
- Turned off Netlify (switching to deploying PR via GitHub actions)

**This PR resolves #(put issue number here, and remove parentheses).**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by jk3587** [comment]
> # [Codecov](https://codecov.io/gh/ericmjl/pyjanitor/pull/787?src=pr&el=h1) Report
> > Merging [#787](https://codecov.io/gh/ericmjl/pyjanitor/pull/787?src=pr&el=desc) ([3abe59d](https://github.com/ericmjl/pyjanitor/commit/3abe59d319036b1434963b440454dcb5430d1c69)) into [dev](https://codecov.io/gh/ericmjl/pyjanitor/commit/c20e4973fa77c2ece189a1721e3e52079771253f?el=desc) ([c20e497](https://github.com/ericmjl/pyjanitor/commit/c20e4973fa77c2ece189a1721e3e52079771253f)) will **decrease** coverage by `96.08%`.
> > The diff coverage is `n/a`.
> 
> ```diff
> @@            Coverage Diff             @@
> ##              dev    #787       +/-   ##
> ==========================================
> - Coverage   96.08%   0.00%   -96.09%     
> ==========================================
>   Files          17      17               
>   Lines        1046    1046               
> ==========================================
> - Hits         1005       0     -1005     
> - Misses         41    1046     +1005     
> ```

Something happened with codecov :/

**Comment by ericmjl** [comment]
@jk3587 yeahhhhh, trying to debug that :frowning:

**Comment by ericmjl** [comment]
@jk3587 OK! We're back in business :)

**Comment by jk3587** [comment]
Is the scope for this PR for ubuntu-latest only or are you planning on also adding the test yaml for windows-latest and macos-latest?

**Comment by ericmjl** [comment]
Yep, that's right @jk3587! Just this PR for now, to keep it simple. We can re-complicate it by doing a matrix build later on. Not sure whether macOS builds are included in GitHub Actions public, but I think it's safe to say that using conda has helped a ton.

The next thing I think we should build is a bot that cuts releases for us haha :smile:.

**Comment by jk3587** [comment]
Re matrix builds - had to google what this was and seems like it is the right path to follow. It seems like macos-latest (if supported by github actions public) would be a drop-in since the steps would be shared. Windows would be a bit more difficult since we'd have to incorporate conditionals and add an entirely new set of commands.

Also, we could remove any azure related dependencies (e.g. pytest-azurepipelines)

**Comment by ericmjl** [comment]
> Also, we could remove any azure related dependencies (e.g. pytest-azurepipelines)

Good point! Let me make those changes.

**Comment by jk3587** [comment]
re build 981c795
coverage.xml wasn't being output.
Looks like pytest-azurepipelines had configured pytest to run with `--cov-report xml`
[relevant lines in pytest-azurepipelines](https://github.com/tonybaloney/pytest-azurepipelines/blob/master/pytest_azurepipelines.py#L69)
[pytest-cov reporting options](https://pytest-cov.readthedocs.io/en/latest/reporting.html)
The workflow might need to be revised to run pytest with that flag to generate the coverage file.

**Comment by ericmjl** [comment]
@loganthomas I pushed up a skeleton YAML file that you can fill out later on, after your interview. All the best for your interview, pray that you have a wonderful presentation and show your best side! :smile:

**Comment by ericmjl** [comment]
@loganthomas I'm going to merge this PR first. I think it'll work. Whenever you have time, please feel free to handle the auto-release Action!

@samukweku can you update your PR with the new changes as soon as we've merged?

**Pull request merged**
