### PR TITLE
[ENH] allow pandas data structures in `complete`

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Deprecate dictionary - be explicit and use a pandas object instead

**This PR improves the `complete` method.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1369--pyjanitor.netlify.app

**Comment by ericmjl** [comment]
@samukweku can I ask, what's the rationale for deprecating passing in a dictionary? As far as I remember, it was a mapping from column name to desired values, and I thought that was quite explicit and flexible at the same time. Not saying we have to reinstate it, but I just wanted to hear your rationale.

**Comment by samukweku** [comment]
@ericmjl it is a bit of explicitness/restriction/more flexibility - i'd say explicitness more - the current implementation allows the dictionary to point to an array or a series or a list or an index - this requires some extra handling. The same approach is solved in a clearer way by just passing a Series/Index that is named. since a Series/Index is in a way a dictionary, it offers the same solution as a dictionary but with more explicitness. The other part is the limitation - with a dictionary you cannot generate a pandas DataFrame or MultiIndex easily - I came across an interesting problem in R that our current approach couldnt solve - whereas with an explicit pandas data structure, the solution becomes easier.  The R question - https://stackoverflow.com/q/67376772/7175713

```py
# converted the R question into a python form
import pandas as pd; import janitor
data = [{'group': 'A', 'subgroup': 1, 'low_end': 5, 'high_end': 10, 'value': 99},
 {'group': 'A', 'subgroup': 2, 'low_end': 10, 'high_end': 15, 'value': 99},
 {'group': 'B', 'subgroup': 2, 'low_end': 10, 'high_end': 15, 'value': 99},
 {'group': 'B', 'subgroup': 2, 'low_end': 15, 'high_end': 20, 'value': 99},
 {'group': 'C', 'subgroup': 1, 'low_end': 25, 'high_end': 30, 'value': 99}]
df = pd.DataFrame(data)
df
  group  subgroup  low_end  high_end  value
0     A         1        5        10     99
1     A         2       10        15     99
2     B         2       10        15     99
3     B         2       15        20     99
4     C         1       25        30     99
```

The aim is to expand `low_end` and `high_end` at the same time - that is `[(5,10),(10,15),(15,20),(20,25),(25,30)]`. Notice in the dataframe above `(20,25)` combination is missing.
One option would be to pass a tuple :
```
In [9]: df.complete('group','subgroup',('low_end','high_end'))
Out[9]: 
   group  subgroup  low_end  high_end  value
0      A         1        5        10   99.0
1      A         1       10        15    NaN
2      A         1       15        20    NaN
3      A         1       25        30    NaN
4      A         2        5        10    NaN
5      A         2       10        15   99.0
6      A         2       15        20    NaN
7      A         2       25        30    NaN
8      B         1        5        10    NaN
9      B         1       10        15    NaN
10     B         1       15        20    NaN
11     B         1       25        30    NaN
12     B         2        5        10    NaN
13     B         2       10        15   99.0
14     B         2       15        20   99.0
15     B         2       25        30    NaN
16     C         1        5        10    NaN
17     C         1       10        15    NaN
18     C         1       15        20    NaN
19     C         1       25        30   99.0
20     C         2        5        10    NaN
21     C         2       10        15    NaN
22     C         2       15        20    NaN
23     C         2       25        30    NaN
```
However, we are missing the `(20,25)` combination. We could pass them individually, but that would just blow up and bring in unnecessary combinations - it would create `(5,10), (5,15), (5,20)...` which the OP does not want.
```
In [10]: df.complete('group','subgroup','low_end','high_end')
Out[10]: 
   group  subgroup  low_end  high_end  value
0      A         1        5        10   99.0
1      A         1        5        15    NaN
2      A         1        5        20    NaN
3      A         1        5        30    NaN
4      A         1       10        10    NaN
..   ...       ...      ...       ...    ...
91     C         2       15        30    NaN
92     C         2       25        10    NaN
93     C         2       25        15    NaN
94     C         2       25        20    NaN
95     C         2       25        30    NaN

[96 rows x 5 columns]
```
A dictionary is the current way of introducing new values, however, at the moment we cannot pass a MultiIndex or DataFrame via a dictionary (the names in the dictionary must already exist in the original DataFrame): 

```
In [16]: high_end = {'high_end':range(df.high_end.min(), df.high_end.max()+5, 5)}

In [17]: low_end = {'low_end':range(df.low_end.min(), df.low_end.max()+5, 5)}

In [18]: dictionary = low_end|high_end

In [19]: dictionary
Out[19]: {'low_end': range(5, 30, 5), 'high_end': range(10, 35, 5)}

In [20]: df.complete('group','subgroup',dictionary)
Out[20]: 
    group  subgroup  low_end  high_end  value
0       A         1        5        10   99.0
1       A         1        5        15    NaN
2       A         1        5        20    NaN
3       A         1        5        25    NaN
4       A         1        5        30    NaN
..    ...       ...      ...       ...    ...
145     C         2       25        10    NaN
146     C         2       25        15    NaN
147     C         2       25        20    NaN
148     C         2       25        25    NaN
149     C         2       25        30    NaN

[150 rows x 5 columns]
```

With this PR however, we can pass a 2D pandas object (MultiIndex/DataFrame), and the `complete` function will take care of the rest: 

```py
In [21]: low_end = range(df.low_end.min(), df.low_end.max()+5, 5)

In [22]: high_end = range(df.high_end.min(), df.high_end.max()+5, 5)
 # we can also use a DataFrame
In [23]: index = pd.MultiIndex.from_arrays([low_end,high_end],names=['low_end','high_end'])

In [24]: df.complete('group','subgroup',index)
Out[24]: 
   group  subgroup  low_end  high_end  value
0      A         1        5        10   99.0
1      A         1       10        15    NaN
2      A         1       15        20    NaN
3      A         1       20        25    NaN    <------ missing combination is introduced
4      A         1       25        30    NaN
5      A         2        5        10    NaN
6      A         2       10        15   99.0
7      A         2       15        20    NaN
8      A         2       20        25    NaN
9      A         2       25        30    NaN
10     B         1        5        10    NaN
11     B         1       10        15    NaN
12     B         1       15        20    NaN
13     B         1       20        25    NaN
14     B         1       25        30    NaN
15     B         2        5        10    NaN
16     B         2       10        15   99.0
17     B         2       15        20   99.0
18     B         2       20        25    NaN
19     B         2       25        30    NaN
20     C         1        5        10    NaN
21     C         1       10        15    NaN
22     C         1       15        20    NaN
23     C         1       20        25    NaN
24     C         1       25        30   99.0
25     C         2        5        10    NaN
26     C         2       10        15    NaN
27     C         2       15        20    NaN
28     C         2       20        25    NaN
29     C         2       25        30    NaN
```

Apologies for a long winded reason, it also gave me a reason to put down my thoughts - thanks for the prompt - really appreciate. Hope this makes sense? I would love your opinion as well.

**Comment by samukweku** [comment]
thanks @ericmjl for the feedback. I'll make changes so the dictionary is not deprecated. This is why I love code reviews - there is always another point of view. thanks!

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
LGTM, thank you @samukweku!

**Pull request merged**
