### PR TITLE
[INF] Update code_check github actions black version

### PR DESCRIPTION
**Pull request by nvamsikrishna05**
# PR Description

Please describe the changes proposed in the pull request:

- pre-commit hooks black version has been updated. github actions black version wasn't updated. Both versions are formatting rules are a bit differently causing conflicts.
- Updated the black version in the code_checks yaml file to match the pre-commit hooks black version.
- Updated the black version in the environment-dev yaml file.

**This PR resolves #846 **

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl
- @loganthomas 
- @samukweku

### CODE REVIEW

**Comment by nvamsikrishna05** [comment]
@ericmjl @loganthomas After updating the black version, black is showing more files to be updated compared to old version of black. Shall I proceed to format the files with new version of black  and update the PR ?

**Comment by ericmjl** [comment]
@nvamsikrishna05 yes, I believe that would be an awesome course of action here! Thank you for handling this!

**Comment by nvamsikrishna05** [comment]
@ericmjl PR has been updated with the newer version of black formatted code also. You can review the changes and merge it.

**Review by ericmjl — APPROVED** [review]
Wonderful stuff, thanks @nvamsikrishna05!

**Comment by ericmjl** [comment]
@nvamsikrishna05 can you ping me via Shortwhale (http://www.shortwhale.com/ericmjl)? I'd like to invite you onto the dev team.

**Comment by nvamsikrishna05** [comment]
@ericmjl Sure. Doing it right now

**Pull request merged**
