### PR TITLE
[ENH] remove select_columns from conditional_join

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- remove deprecated `select_columns` function from other functions/tests
- use align instead of merge for left/right join
- add support for timedelta dtype

**This PR builds on #1288 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
🚀 Deployed on https://deploy-preview-1297--pyjanitor.netlify.app

**Review by ericmjl — APPROVED** [review]

**Comment by ericmjl** [comment]
# GitBot Summary of Changes

The pull request includes several changes across multiple files, primarily focusing on enhancing the `conditional_join` function and updating the `select` function usage:

1. In `CHANGELOG.md`, a new enhancement is added to the list, stating that `conditional_join` now supports timedelta dtype.

2. In `conditional_join.py`, the `conditional_join` function is updated to support timedelta dtype. The function now supports efficient joins on inequality operators. The function's documentation is updated to reflect these changes. Several examples are added to illustrate the new functionality.

3. In `deconcatenate_column.py`, `impute.py`, `move.py`, `pivot.py`, `utils.py`, `io.py`, and `test_clean_names.py`, the usage of `select_columns` is replaced with `select`.

4. In `test_conditional_join.py`, new test cases are added to verify the correct behavior of the updated `conditional_join` function.

5. In `xlsx_cells` function in `io.py`, the usage of `select_columns` is replaced with `select`.

6. In `test_clean_names.py`, the usage of `select_columns` is replaced with `select` in the test cases.

7. In `test_conditional_join.py`, new test cases are added to verify the correct behavior of the updated `conditional_join` function, especially with the new support for timedelta dtype.

cc: @samukweku, please check for correctness!

**Comment by ericmjl** [comment]
@samukweku I think we're good to merge, right? I've already approved the changes, and all tests pass so far.

**Comment by samukweku** [comment]
@ericmjl yes it is ok to merge. Thanks

**Pull request merged**
