### PR TITLE
Ignore PDFs in readthedocs build

### LINKED ISSUE #7972: Build termninated due to inactivity #13136208
## Details

* Read the Docs project URL: https://github.com/ericmjl/pyjanitor
* Build URL (if applicable): https://readthedocs.org/projects/pyjanitor/builds/13146742/
* Read the Docs username (if applicable): samukweku

## Expected Result
Build should complete

## Actual Result
Build terminated due to inactivity

readthedocs

Not sure why it failed. Please help in resolving this issue.

### PR DESCRIPTION
**Pull request by ericmjl**
Should resolve https://github.com/readthedocs/readthedocs.org/issues/7972.

### CODE REVIEW

**Review by samukweku — APPROVED** [review]

**Comment by ericmjl** [comment]
Looks like the build passes: https://readthedocs.org/projects/pyjanitor/builds/13156461/

**Comment by samukweku** [comment]
@ericmjl , any idea why it is not the latest docs? For instance [select_columns](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.select_columns.html#janitor.select_columns) is not showing the latest changes. Same for some of the example notebooks, as well as some other functions. Unless I'm viewing the wrong docs ...

**Comment by ericmjl** [comment]
@samukweku I think readthedocs is redirecting to the last published version of `dev`. I get the same issue myself. Looking at the build for this branch, though, tells me it _might_ work. We probably can merge and see what happens on `dev`.

**Review by loganthomas — APPROVED** [review]
LGTM! Thanks Eric.

**Pull request merged**
